
echo "$0: configuring clocks"

# The MGT ref clock of the Kintex FPGA is generated by the main PLL. Therefore, the FPGA must first be put into reset state.
pl-reset.py 0
echo "$0: put Kintex into reset state"

si-labs-clk-config.py 0x76 /opt/mtca-tech-lab/damc-motctrl/clock_config/0x76_mainpll.txt 2>&1

sleep 0.1
pl-reset.py 1
echo "$0: released Kintex from reset state"

echo "$0: clock config done"
